<!-- <h1>This is my template, there are many like it, but this one is mine.</h1>
<script type="text/javascript">
    requirejs(['Pulsestorm_JavascriptInitTutorial/example'],function(example){
        alert("Loaded");
        console.log(example);
    });
</script>



<div id="one" class="foo">Hello World</div>
<div id="two" class="foo">Goodbye World</div>

        "*"
        "#one" 

<script type="text/x-magento-init">
    {
        ".foo": {
            "Pulsestorm_JavascriptInitTutorial/example":{"config":"value"}
        }
    }
</script>
 -->

<div data-mage-init='{"Pulsestorm_JavascriptInitTutorial/example": {"another":"example"}}'>A single div</div>
