    <div class="content" data-role="content" aria-labelledby="block-charity-heading">
        <form id="charity-form"
              action="#"
              method="post"
              value="0" />
            <?php //echo $block->getBlockHtml('formkey') ?>
                <div class="field">
                    <div class="control">
                         <select id="charity_id" name="charity_id">                     
                                <option value="test1">test1</option>
                                <option value="test2">test2</option>
                          </select>
                    </div>
                </div>

        </form>         
    </div>      
</div>  