<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php
/**
 * @var \Amasty\Shopby\Block\Navigation\FilterCollapsing $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>

<script type="text/x-magento-init">
    {
        ".sidebar #narrow-by-list": {
            "accordion": {
                "multipleCollapsible": true,
                "active": [<?= $escaper->escapeHtml(implode(",", $block->getFiltersExpanded()))?>]
            }
        }
    }
</script>
